MODULE FORTUTF
    USE FUTF_ASSERTIONS
    USE FUTF_SPECIALS
    USE FTF_STRING_CHECK
    USE FUTF_SUITE
    USE FUTF_UTILITIES
    IMPLICIT NONE
    PRIVATE

    PUBLIC :: ASSERT_EQUAL, ASSERT_ALMOST_EQUAL, ASSERT_TRUE, ASSERT_FALSE, &
        & ASSERT_NOT_EQUAL, ASSERT_LESS_THAN, ASSERT_LESS_THAN_EQUAL, &
        & ASSERT_GREATER_THAN, ASSERT_GREATER_THAN_EQUAL, ASSERT_IS_INT, &
        & ASSERT_IS_REAL, ASSERT_IS_CHARACTER, ASSERT_IS_COMPLEX, &
        & ASSERT_ARRAY_CONTAINS, INT_KIND_1BYTE, INT_KIND_2BYTE, &
        & INT_KIND_4BYTE, INT_KIND_8BYTE, REAL_KIND_4BYTE, REAL_KIND_8BYTE
    PUBLIC :: FAIL, SUCCEED
    PUBLIC :: STRING_CONTAINS, STRING_HAS_SUFFIX, STRING_HAS_PREFIX
    PUBLIC :: FUTF_PASSED, FUTF_TOTAL, FUTF_EXIT_CODE, IDENTIFIER, TEST_NAMES, &
        & TEST_RESULTS, INFO_STRINGS, TAG_TEST, REGISTER_PASSED, &
        & REGISTER_FAILED, TEST_SUMMARY, FAILED_TEST_SUMMARY, &
        & RESET_LAST_TEST_STATUS
    PUBLIC :: APPEND_CHAR, APPEND_INT, GET_INDEX_STRARRAY
END MODULE FORTUTF
