name: FortUTF macOS GFortran 16

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'macOS Latest'
    runs-on: 'macos-latest'

    steps:
      - uses: actions/checkout@v7
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.x'
      - name: Install GFortran macOS
        run: brew install gcc-16
      - name: Build Tests
        run: |
            gfortran --version
            cmake -H. -Bbuild -DBUILD_TESTS=ON -DCMAKE_Fortran_COMPILER=$(which gfortran)
            cmake --build build
      - name: Run Tests
        run: |
             ./build/FortUTF_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
      - name: Run Test List
        run: |
             ./build/FortUTF_Tests TEST_FAIL_EQUAL_CHAR TEST_EQUAL_CHAR
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
